lang: "de"

engine: knitr

project:
  type: book
  output-dir: "docs"

book:
  announcement:
    icon: info-circle
    dismissable: true
    content: "**Alert** - this is some information that you should pay attention to"
    type: primary
    position: below-navbar
  title: "Kausalanalyse und maschinelles Lernen mit R"
  reader-mode: true
  author: 
    - Martin C. Arnold 
    - Christoph Hanck
  date: "November 2023"
  chapters:
    - index.qmd
    - part: "Grundlagen"
      chapters:
        - R_Einfuehrung.qmd
        - RR.qmd
        - Reg.qmd
        - Simulation.qmd
    - part: "Kausale Inferenz"
      chapters:
        - Matching.qmd
        - FixedEffects.qmd
        - IV.qmd
        - DiD.qmd
        - EventStudies.qmd
        - RDD.qmd
        - SyntheticControl.qmd
    - part: "Machine Learning"
      chapters:
        - RegReg.qmd
        - svm.qmd
        - trees.qmd
        - Machine Learning.qmd
    # - part: Übungsaufgaben
    #   chapters:
    #     - ex.qmd
    #     - ex_RR.qmd
    #     - ex_simulation.qmd
    - Literatur.qmd
  repo-url: https://github.com/mca91/kasa_book
  repo-branch: main
  repo-actions: [edit, issue]
  search:
    location: navbar
    type: overlay
  cookie-consent: false
  sidebar:
    title: "<a href='/index.html'>Kausalanalyse und maschinelles Lernen mit R</a>"

bibliography: references.bib

execute: 
  warning: false

format:
  live-html:
    engine: knitr
    grid: 
      body-width: 920px
      margin-width: 350px
    fontsize: "20px"
    theme: cosmo
    cap-location: margin
    code-link: true
    linkcolor: darkgreen
    toc: true
    toc-depth: 4
    toc-location: left
    toc-title: "<a href='/index.html'>Übersicht</a>"
    reference-location: margin
    include-in-header:
      file: 'mathjax.html' 
    code-tools: true
    css: custom_styles.css
    cell-options:
      completion: true
      timelimit: 60

  pdf:
    pdf-engine: pdflatex
    papersize: a4
    linestretch: 1.2
    fig-pos: t

    geometry:
      - inner=3cm
      - outer=5cm
      - top=3cm
      - bottom=4cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
      
    keep-tex: true
    
    include-in-header:
       text: |
         \usepackage{lscape}
         \newcommand{\blandscape}{\begin{landscape}}
         \newcommand{\elandscape}{\end{landscape}}
         \usepackage{float}
         \floatplacement{table}{t}
         \usepackage{amsmath, amssymb, amsthm, amstext}
         \usepackage{mlmodern}
         \usepackage[T1]{fontenc}
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
        text: |
          \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
          showspaces = false,
          showtabs = false,
          breaksymbolleft={},
          breaklines
          }
          
editor: source
  