lang: "de"

engine: knitr

project:
  type: book
  output-dir: "docs"

book:
  title: "Kausalanalyse und maschinelles Lernen mit R"
  description: '*Kausalanalyse und Maschinelles Lernen mit R* (KMLR) ist ein innovatives Online-Lehrbuch, das Studierende der Wirtschaftswissenschaften in moderne statistische Methoden und deren ökonometrische Anwendungen einführt. Das interaktive Kompendium für quantitative Lehrveranstaltungen verbindet theoretische Grundlagen mit praktischer Anwendung durch die Möglichkeit, R-Code direkt im Browser auszuführen. Von den statistischen Grundlagen über fortgeschrittene Methoden der Kausalanalyse bis hin zu Machine Learning-Techniken bietet das Buch einen umfassenden Einblick in fortschrittliche quantitative Forschungsmethoden. Besonders wertvoll für Studierende sind die zahlreichen interaktiven Visualisierungen und praxisnahen Fallstudien mit wirtschaftswissenschaftlichem Fokus, die ein tiefes Verständnis der ökonometrischen Methoden fördern und Kompetenzen in reproduzierbarer Forschung mit dem R-Ökosystem vermitteln.'
  reader-mode: true
  author: 
    - name: Martin C. Arnold 
      affiliation: University of Duisburg-Essen
      affiliation-url: https://www.oek.wiwi.uni-due.de/team/martin-christopher-arnold/
    - name: Christoph Hanck
      affiliation: University of Duisburg-Essen
      affiliation-url: https://www.oek.wiwi.uni-due.de/team/christoph-hanck/
  date: "09.10.2024"
  body-header: |
    <div class="callout callout-style-simple callout-note">
    <div class="callout-body d-flex">
    <div class="callout-icon-container">
    <i class="callout-icon"></i>
    </div>
    <div class="callout-body-container">
    <p><strong>Hinweis</strong></p>
    <p>Für eine optimale technische Stabilität empfehlen wir, dieses Online-Lehrbuch auf einem Notebook oder Desktop-Computer zu nutzen. Die interaktiven Komponente, insbesondere die R-Konsole (WebR), sind rechenintensiv und funktionieren auf mobilen Geräten nur eingeschränkt.</p>
    </div>
    </div>
    </div>
  sharing: [twitter, facebook, linkedin]
  twitter-card: true
  chapters:
    - index.qmd
    - part: "Grundlagen"
      chapters:
        - R_Einfuehrung.qmd
        - RR.qmd
        - Reg.qmd
        - Simulation.qmd
    - part: "Kausale Inferenz"
      chapters:
        - Matching.qmd
        - FixedEffects.qmd
        - IV.qmd
        - DiD.qmd
        - EventStudies.qmd
        - RDD.qmd
        - SyntheticControl.qmd
    - part: "Machine Learning"
      chapters:
        - RegReg.qmd
        - svm.qmd
        - trees.qmd
        - Machine Learning.qmd
    # - part: Übungsaufgaben
    #   chapters:
    #     - ex.qmd
    #     - ex_RR.qmd
    #     - ex_simulation.qmd
    - Literatur.qmd
  repo-url: https://github.com/mca91/kasa_book
  repo-branch: main
  repo-actions: [edit, issue, source]
  search: true
  cookie-consent: false
  navbar:
    background: light
  sidebar:
    title: "<a href='/index.html'>Kausalanalyse und maschinelles Lernen mit R</a>"

bibliography: references.bib
citation:
  type: book
google-scholar: true

format:
  live-html:
    engine: knitr
    grid: 
      gutter-width: 50px
      body-width: 920px
      margin-width: 350px
    fontsize: "20px"
    theme: 
      light: [cosmo, theme-dark.scss]
    cap-location: margin
    code-link: true
    linkcolor: darkgreen
    toc: true
    toc-depth: 4
    toc-location: right
    toc-title: "<a href='/index.html'>Übersicht</a>"
    reference-location: margin
    include-in-header:
      file: 'mathjax.html' 
    code-tools: true
    css: custom_styles.css
    webr:
      cell-options:
        warning: false
        message: false
        completion: true
        timelimit: 60

  pdf:
    pdf-engine: pdflatex
    papersize: a4
    linestretch: 1.2
    fig-pos: t

    geometry:
      - inner=3cm
      - outer=5cm
      - top=3cm
      - bottom=4cm
      - headsep=22pt
      - headheight=11pt
      - footskip=33pt
      - ignorehead
      - ignorefoot
      - heightrounded
      
    keep-tex: true
    
    include-in-header:
       text: |
         \usepackage{lscape}
         \newcommand{\blandscape}{\begin{landscape}}
         \newcommand{\elandscape}{\end{landscape}}
         \usepackage{float}
         \floatplacement{table}{t}
         \usepackage{amsmath, amssymb, amsthm, amstext}
         \usepackage{mlmodern}
         \usepackage[T1]{fontenc}
         \usepackage{fvextra}
         \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
    include-before-body:
        text: |
          \RecustomVerbatimEnvironment{verbatim}{Verbatim}{
          showspaces = false,
          showtabs = false,
          breaksymbolleft={},
          breaklines
          }
          
editor: source
  