---
format: live-html
engine: knitr
---

# Reproduzierbarkeit {.unnumbered}

1. Erstelle ein RMarkdown-Dokument, das zu einem HTML-Dokument kompiliert wird. Das Dokument sollte aus zwei Abschnitten bestehen:
  
    - *Crime Incidents Report Data*
    - *Explorative Datenanalyse*
  
2. Im ersten Abschnitt des Dokuments sollen die neusten [hier](https://data.boston.gov/dataset/crime-incident-reports-august-2015-to-date-source-new-system) verfügbaren "*Crime Incident Reports*" eingelesen werden. Füge Informationen über die Quelle der Daten als Textblock hinzu hinzu und liste alle verfügbaren Variablen mit einer kurzen Beschreibung.

    **Hinweis**: Die Tabelle *RMS_Crime_Incident_Field_Explanation* enthält eine Beschreibung der Variablen.

3. Konfiguriere die Code-Chunks so, dass die Daten nicht jedes mal (neu) eingelesen werden, wenn das Dokument kompiliert wird.

4. Verwende den zweiten Abschnitt für eine kleine explorative Datenanalyse. Hierbei sollte mindests eine Grafik und eine Tabelle erstellt werden.

5. Setze eine globale Chunk-Option, die sämtliche Code-Chunks im HTML-Output-Dokument "einklappt" und per Klick ausklappbar macht.

6. Kompiliere die `.Rmd`-Datei zu einem PDF-Dokument. Hierzu muss $\LaTeX$ installiert sein (siehe @sec-genrmd).