<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Simulation – Kausalanalyse mit R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Matching.html" rel="next">
<link href="./Reg.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./R_Einfuehrung.html">Grundlagen</a></li><li class="breadcrumb-item"><a href="./Simulation.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Simulation</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./"></a><a href="./index.html">Kausalanalyse mit R</a> 
        <div class="sidebar-tools-main">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Lesemodus umschalten">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Grundlagen</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./R_Einfuehrung.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Statistische Programmierung mit R</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Übungsaufgaben</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Reg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Simulation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Simulation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Kausale Inferenz</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Matching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./FixedEffects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Panel-Daten</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./IV.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">IV-Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./DiD.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Difference-in-Differences</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./EventStudies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Event Studies</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RDD.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regression Discontiniuty Designs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./SyntheticControl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Synthetic Control</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Machine Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RegReg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Regularisierte Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Machine Learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Machine Learning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Literatur.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literatur</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#sec-simspv" id="toc-sec-simspv" class="nav-link active" data-scroll-target="#sec-simspv"><span class="header-section-number">5.1</span> Simulation der Stichprobenverteilung eines Schätzers</a>
  <ul class="collapse">
  <li><a href="#simulation-mit-nicht-normalen-daten" id="toc-simulation-mit-nicht-normalen-daten" class="nav-link" data-scroll-target="#simulation-mit-nicht-normalen-daten"><span class="header-section-number">5.1.1</span> Simulation mit nicht-normalen Daten</a></li>
  <li><a href="#sec-simbiasconf" id="toc-sec-simbiasconf" class="nav-link" data-scroll-target="#sec-simbiasconf"><span class="header-section-number">5.1.2</span> Regression: Verzerrung durch Confounder</a></li>
  <li><a href="#regression-verzerrung-durch-collider" id="toc-regression-verzerrung-durch-collider" class="nav-link" data-scroll-target="#regression-verzerrung-durch-collider"><span class="header-section-number">5.1.3</span> Regression: Verzerrung durch Collider</a></li>
  </ul></li>
  <li><a href="#regression-durchschnittlicher-behandlungseffekt" id="toc-regression-durchschnittlicher-behandlungseffekt" class="nav-link" data-scroll-target="#regression-durchschnittlicher-behandlungseffekt"><span class="header-section-number">5.2</span> Regression: Durchschnittlicher Behandlungseffekt</a></li>
  <li><a href="#verletzung-von-modellannahmen-heteroskedastizität" id="toc-verletzung-von-modellannahmen-heteroskedastizität" class="nav-link" data-scroll-target="#verletzung-von-modellannahmen-heteroskedastizität"><span class="header-section-number">5.3</span> Verletzung von Modellannahmen: Heteroskedastizität</a></li>
  <li><a href="#der-bootstrap" id="toc-der-bootstrap" class="nav-link" data-scroll-target="#der-bootstrap"><span class="header-section-number">5.4</span> Der Bootstrap</a>
  <ul class="collapse">
  <li><a href="#interaktive-visualisierung-des-bootstraps" id="toc-interaktive-visualisierung-des-bootstraps" class="nav-link" data-scroll-target="#interaktive-visualisierung-des-bootstraps"><span class="header-section-number">5.4.1</span> Interaktive Visualisierung des Bootstraps</a></li>
  <li><a href="#bootstrap-mit-r-durchführen" id="toc-bootstrap-mit-r-durchführen" class="nav-link" data-scroll-target="#bootstrap-mit-r-durchführen"><span class="header-section-number">5.4.2</span> Bootstrap mit R durchführen</a></li>
  </ul></li>
  <li><a href="#zusammenfassung" id="toc-zusammenfassung" class="nav-link" data-scroll-target="#zusammenfassung"><span class="header-section-number">6</span> Zusammenfassung</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./R_Einfuehrung.html">Grundlagen</a></li><li class="breadcrumb-item"><a href="./Simulation.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Simulation</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-sim" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Simulation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<style>

div.sidebar-item-container .active {
  color: darkgreen;
  font-weight: 550;
}

div.sidebar-item-container:hover {
  color: darkgreen;
}

.sidebar nav[role=doc-toc] ul>li>a.active,
.sidebar nav[role=doc-toc] ul>li>ul>li>a.active,
.sidebar nav[role=doc-toc] ul>li>ul>li>ul>li>a.active {
  border-left: 1px solid darkgreen !important;
  color: darkgreen !important;
  font-weight: 550;
}

.sidebar nav[role=doc-toc] ul>li>a:hover,
.sidebar nav[role=doc-toc] ul>li>ul>li>a:hover,
.sidebar nav[role=doc-toc] ul>li>ul>li>ul>li>a:hover {
  color: darkgreen !important;
}

.qwebr-icon-run-code {
  color: white;
  padding-right: 2px;
}

.qwebr-button-run, .qwebr-button-reset, .qwebr-button-copy {
  background-color:  rgba(0, 0, 0, 0) !important;
  border-style: none;
  font-weight: 400;
  color: white !important; 
  transition: none;
}

.qwebr-button-run:hover, .qwebr-button-reset:hover, .qwebr-button-copy:hover {
    border-radius: 6px 6px 6px 6px;
    border-color: darkgreen !important;
    border: 1px 1px 1px 1px;
}

.qwebr-button-run {
  font-weight: 600;
}

.qwebr-editor-toolbar {
  width: 100%;
  display: flex;
  justify-content: space-between;
  box-sizing: border-box;
  border-radius: 6px 6px 0 0;
  background-color: darkgreen !important;
  border: 1px solid darkgreen !important;
  padding: 0 0; 
  transition: color .1s ease-in-out, background-color .1s ease-in-out,border-color .1s ease-in-out,box-shadow .1s ease-in-out !important;
}

.qwebr-editor-toolbar:hover {
  background-color: white !important;
  border-color: darkgreen;
  border: 1px 1px 0px 1px;
}

.qwebr-editor-toolbar:hover * {
  color: darkgreen !important;
}

/*
.qwebr-editor {
  border-radius: 0 0 6px 6px !important;
  border: 1px solid darkgreen !important;
}
*/

.qwebr-output-code-area {
  border-radius: 0 0 6px 6px !important;
  padding-left: 3.7em;
  padding-top: .5em;
  margin-bottom: 1em;
  /*background-color:rgba(250,250,250,.9) !important;*/
}

.qwebr-output-code-area div {
  padding-bottom: 12px;
}

.qwebr-output-graph-area {
  margin-bottom: 1.5em;
}

.monaco-editor .lines-content {
  background: none;
}

.monaco-editor {
  outline-width: 0;
  background: none !important;
}

.monaco-editor .margin {
  background: none !important;
}

.monaco-editor .line-numbers {
  color:black !important;
}

.box-shadow {
    box-shadow: 0px 1px 2px rgba(0,0,0,.1),
                0px 3px 7px rgba(0,0,0,.1),
                0px 12px 30px rgba(0,0,0,.08);
    border-radius: 0 0 6px 6px;
}


</style>
<p>Bei der Analyse quantitativer Methoden treten häufig Fragestellungen auf, die sich rein mathematisch nur schwer oder gar nicht lösen lassen. So ist es sogar in einfachsten ökonometrischen Modellen oft unmöglich, die exakte Verteilung von Koeffizientenschätzern unter “realistischen” Bedingungen (etwa eine endliche Stichprobengröße und schwache Annahmen über die Verteilung der Fehlerterme) formal zu bestimmen. Asymptotische Theorie kann dann helfen, indem eine Approximation der Stichproben-Eigenschaften eines Schätzers aus Eigenschaften der asymptotischen Verteilung abgeleitet werden. Häufig sind solche Approximationen jedoch nur bei großen Stichproben verlässlich. Wichtige Eigenschaften von Schätzern kausaler Effekte in empirischen Anwendungen, wie die Varianz der Schätzung oder das zu erwartende Außmaß der Verzerrung bei Verletzungen von Modellannahmen hingegen können mit asymptotischer Theorie oftmals gar nicht approximiert werden.</p>
<p>Um diese Schwierigkeiten zu überwinden, können wir Simulationstechniken (Monte-Carlo-Methoden) verwenden. In Monte-Carlo-Simulationen wird die Möglichkeit der Erzeugung von Pseudozufallszahlen mit Computern und ihre Rechenleistung genutzt, um eine Vielzahl von Datensätzen gemäß eines interessierenden datenerzeugenden Prozess (DGP) zu generieren. Anhand dieser simulierten Datensätze können wir die Stichprobenverteilung von Schätzern approximieren und so die statistischen Eigenschaften für verschiedene Parameterwerte des DGP analysieren. Insbesondere erlauben <em>Monte-Carlo-Studien</em> den Vergleich verschiedener Schätzfunktionen hinsichtlich ihrer Robustheit gegenüber Verletzungen zugrundeliegender Annahmen über den DGP. Der <em>Bootstrap</em> <span class="citation" data-cites="Efron1979">(<a href="Literatur.html#ref-Efron1979" role="doc-biblioref">Efron 1979</a>)</span> ist eine simulations-basierte Methode, um gültige statistische Inferenz in empirischen Anwendungen zu gewährleisten, wenn Modellannahmen derart verletzt sind, dass asymptotische kritische Werte (sogar für große Stichproben) ungültig sind.</p>
<p>In diesem Kapitel erläutern wir Grundlagen in der Anwendung von Simulations-Methoden mit R und diskutieren Beispiele für die Schätzung kausaler Effekte mit Regressionsmodellen.</p>
<section id="sec-simspv" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-simspv"><span class="header-section-number">5.1</span> Simulation der Stichprobenverteilung eines Schätzers</h2>
<p>Zur Illustration der Simulation von Stichprobenverteilungen eines Schätzers betrachten wir zunächst das kanonische Beispiel der Schätzung des Erwartungswerts <span class="math inline">\(\mu_X\)</span> einer normalverteilen Zufallsvariable <span class="math inline">\(X\)</span> anhand einer <span class="math inline">\(n\)</span>-elementigen Stichprobe, <span class="math display">\[\begin{align}
  X_i \sim\,u.i.v. N(\mu_X,\ \sigma_X^2), \quad i=1,\dots,n.\label{eq:distx}
\end{align}\]</span> Die Vorschrift <span class="math inline">\(\eqref{eq:distx}\)</span> ist der <em>datenerzeugende Prozess</em> (DGP)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. Das arithmetische Mittel der <span class="math inline">\(X_i\)</span>, <span class="math display">\[\begin{align*}
  \overline{X} := \sum_{i=1}^n X_i,
\end{align*}\]</span> ist ein <em>konsistenter Schätzer</em> für <span class="math inline">\(\mu_X\)</span> und hat (aufgrund der Normalverteilung der <span class="math inline">\(X_i\)</span>) die formal herleitbare Eigenschaft, dass die Stichprobenverteilung normal ist<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>, <span class="math display">\[\begin{align*}
  \overline{X} \sim N(\mu_X, \sigma_X^2 / n), \qquad \overline{X}\xrightarrow{p}\mu_X.
\end{align*}\]</span></p>
<p>Wir können die Eigenschaften von <span class="math inline">\(\overline{X}\)</span> mit wenig Aufwand in R prüfen indem wir die Stichprobenentnahme durch wiederholtes Ziehen einer (großen) Anzahl von <span class="math inline">\(N\)</span> Stichproben aus der <em>Populationsverteilung</em> von <span class="math inline">\(X\)</span> gemäß der Vorschrift <span class="math inline">\(\eqref{eq:distx}\)</span> simulieren und jeweils <span class="math inline">\(\overline{X}\)</span> für diese simulierten Stichproben berechnen. Wir simulieren so Züge aus der Stichprobenverteilung von <span class="math inline">\(\overline{X}\)</span>, deren Eigenschaften – in Abhängigkeit von <span class="math inline">\(\mu_X\)</span>, <span class="math inline">\(\sigma_X^2\)</span> und <span class="math inline">\(n\)</span> – wir anhand der Realisierungen von <span class="math inline">\(\overline{X}\)</span> ableiten können. In den nachfolgenden Code-Beispielen wählen wir <span class="math display">\[\begin{align*}
  \mu_X = 50,\quad \sigma_X^2=12^2,\quad n = 50.
\end{align*}\]</span></p>
<p>Eine einfache Zufallsstichprobe von <span class="math inline">\(X\)</span> erzeugen wir mit <code>rnorm()</code> und berechnen das arithmetische Mittel mit <code>mean()</code>.</p>
<pre class="{webr-r}"><code>#| autorun: true
library(dplyr)

# Seed für Reproduzierbarkeit
set.seed(1234)

# Parameter der Simulation
n &lt;- 50
mu_X &lt;- 50
sigma_X &lt;- 12

# Stichprobe ziehen, Mittel berechnen
mean(
  rnorm(
    n = n, 
    mean = mu_X, 
    sd = sigma_X
  )
)</code></pre>
<p>Dieses einfache Simulationsexperiment mit <span class="math inline">\(N=1\)</span> ergibt zwar eine Schätzung des Erwartungswerts von <span class="math inline">\(X\)</span> nahe des wahren Werts <span class="math inline">\(\mu_X = 50\)</span>, ist jedoch wenig informativ über die Qualität des Schätzers, d.h. die Eigenschaften der Stichprobenverteilung von <span class="math inline">\(\overline{X}\)</span>. Diese <em>Realisation</em> könnte zufällig nahe bei <span class="math inline">\(\mu_X = 50\)</span> liegen, obwohl die Stichprobenverteilung <span class="math inline">\(\overline{X}\)</span> einen von <span class="math inline">\(50\)</span> verschiedenen Erwartungswert hat und/oder eine große Varianz aufweist.</p>
<p>Um die Stichprobenverteilung zu simulieren, wiederholen wir das Simulationsexperiment <span class="math inline">\(N=1000\)</span> mal: Wir erzeugen <span class="math inline">\(N=1000\)</span> Realisierungen aus der Stichprobenverteilung von <span class="math inline">\(\overline{X}\)</span> für die gewählten Parameter. Hierfür verwenden wir <em>Iteration</em> in R: Eine <code>for()</code>-Schleife wiederholt das Simulationsexperiment über <code>1:N</code> Iterationen und speichert das Ergebnis des <code>j</code>-ten Experiments in einem zuvor definierten numerischen Vektor <code>sim_est</code>.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" aria-current="page">Iteration mit <code>for()-Schleife</code></a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Iteration mit <code>purrr</code></a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<pre class="{webr-r}"><code>#| autorun: true
# Parameter für Iteration
N &lt;- 1000
sim_est &lt;- numeric(N)

set.seed(1234)

# Simulation durchführen
for (j in 1:N) {
  sim_est[j] &lt;- mean(
    x = rnorm(
      n = n, 
      mean = 50, 
      sd = 12
    )
  )
}

# Statistische Zusammenfassung
tibble(sim_est) %&gt;%
    summarise(
        mean_Xbar = mean(sim_est),
        sd_Xbar = sd(sim_est)
    )</code></pre>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<pre class="{webr-r}"><code>#| autorun: true
library(purrr)

# Parameter
N &lt;- 1000

set.seed(1234)

# Simulation mit purrr
sim_est &lt;- map_dbl(
  .x = 1:N, 
  .f =  ~ mean(
    x = rnorm(
      n = n, 
      mean = 50, 
      sd = 12
    )
  )
)

# Statistische Zusammenfassung
tibble(sim_est) %&gt;%
    summarise(
        mean_Xbar = mean(sim_est),
        sd_Xbar = sd(sim_est)
    )</code></pre>
</div>
</div>
</div>
<p>Die zusammenfassenden Statistiken sind <em>Schätzungen</em> der Verteilungseigenschaften von <span class="math inline">\(\overline{X}\)</span>. Da wir die Anzahl der Replikation <span class="math inline">\(N\)</span> selber wählen, können wir die wahren Parameter theoretisch “beliebig” genau approximieren: Lediglich die Rechenleistung des Computers limitiert die Güte dieser Approximation. In vielen Anwendungen liefert eine vierstellige Zahl an Simulationsdurchläufen gute Approximationen. Tatsächlich liegen die simulierten Parameter der Stichprobenverteilung von <span class="math inline">\(\overline{X}\)</span> nahe bei den wahren Werten.</p>
<pre class="{webr-r}"><code>#| autorun: true
# Simulierter Erwartungswert der Stichprobenverteilung
mean(sim_est)

# Theoretische Standardabweichung
12/sqrt(n)

# Simulierte Standardabweichung der Stichprobenverteilung
sd(sim_est)</code></pre>
<p>Für einen grafischen Vergleich der simulierten Stichprobenverteilung mit der theoretischen <span class="math inline">\(N(50, 12^2/50)\)</span>-Verteilung plotten wir die theoretische Dichte sowie ein Dichte-Histogramm der simulierten Züge von <span class="math inline">\(\overline{X}\)</span> in <code>sim_est</code>.</p>
<pre class="{webr-r}"><code>#| autorun: true
library(ggplot2)

# Simulierte und theoretische Verteilungen des Schätzers plotten
tibble(est = sim_est) %&gt;%
    ggplot(
        mapping = aes(x = sim_est)
    ) +
    geom_histogram(
        mapping = aes(y = after_stat(density)), 
        bins = 20, 
        fill = "lightgray", 
        color = "white"
        ) +
    stat_function(
        fun = dnorm, 
        args = list(
            mean = 50, 
            sd = 12/sqrt(n)
        ), 
        color = "red",
        lty = 2
    ) +
    labs(title = "Simulierte Verteilung des Stichprobenmittels") +
    theme_cowplot()</code></pre>
<p>Die Abbildung zeigt, dass die simulierte Stichprobenverteilung (graues Dichte-Histogramm) die Dichte der theoretischen Verteilung (gestrichelte Linie) gut approximiert.</p>
<section id="simulation-mit-nicht-normalen-daten" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="simulation-mit-nicht-normalen-daten"><span class="header-section-number">5.1.1</span> Simulation mit nicht-normalen Daten</h3>
<p>Simulationen sind insbesondere dann hilfreich, wenn die Stichproben-Eigenschaften eines Schätzers <em>unbekannt</em> sind. Im nachfolgenden Beispiel wiederholen wir die Simulation für eine Log-normal-verteilte Zufallsvariable<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> <span class="math inline">\(X\)</span> mit Erwartungswert <span class="math inline">\(\mu_X = 50\)</span> und plotten die geschätzten Dichtefunktionen der Stichprobenverteilungen von <span class="math inline">\(\overline{X}\)</span> für einen Vergleich.</p>
<pre class="{webr-r}"><code>#| autorun: true
library(tidyr)

set.seed(1234)

# Parameter
n &lt;- 50
N &lt;- 1000

# Simulation durchführe, Ergebnisse sammeln
df &lt;- tibble(
  `Normal` = sim_est, 
  `log-Normal` = map_dbl(
    .x = 1:N, 
    .f =  ~ mean(
      x = rlnorm(
        n = n, 
        meanlog = log(50) - 1/2, 
        sdlog = 1
      ) 
    )
  )
)

# Gesch. Dichtefunktionen plotten
df %&gt;% 
  pivot_longer(
    cols = everything(), 
    names_to = "Population"
  ) %&gt;%
  ggplot(
    mapping = aes(
      x = value, 
      col = Population
    )
  ) +
  geom_density() +
  theme_cowplot() +
  labs(title = "Stichprobenverteilung bei log-normaler Population") +
  theme(legend.position = "top")</code></pre>
<p>Die funktionale Form der Stichprobenverteilung von <span class="math inline">\(\overline{X}\)</span> für eine log-normalverteilte Population ist unbekannt. Unsere Simulation erlaubt jedoch Rückschlüsse auf Eigenschaften dieser Verteilung: Die Verteilung ist rechtsschief und weißt eine höhere Varianz auf als die Stichprobenverteilung von <span class="math inline">\(\overline{X}\)</span> für die normal-verteilte Population.</p>
</section>
<section id="sec-simbiasconf" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="sec-simbiasconf"><span class="header-section-number">5.1.2</span> Regression: Verzerrung durch Confounder</h3>
<p>Der DGP in <a href="#fig-simconf" class="quarto-xref">Abbildung&nbsp;<span>5.1</span></a> zeigt eine typische Situation, in der wir den kausalen Effekt von <span class="math inline">\(X\)</span> auf <span class="math inline">\(Y\)</span> nicht ohne Weiteres mit Regression identifizieren können: Die Variablen <span class="math inline">\(U\)</span> und <span class="math inline">\(e\)</span> sind unbeobachtbar. <span class="math inline">\(e\)</span> ist ein unsystematischer Fehler, der lediglich <span class="math inline">\(Y\)</span> beeinflusst. Die Variable <span class="math inline">\(U\)</span> hingegen beeinflusst sowohl <span class="math inline">\(X\)</span> als auch <span class="math inline">\(Y\)</span> und ist damit eine Backdoor-Variable: <span class="math inline">\(U\)</span> ist ein <em>Counfounder</em>, sodass der kausale Effekt von <span class="math inline">\(X\)</span> auf <span class="math inline">\(Y\)</span> in einer Regression, die nicht für den Effekt von <span class="math inline">\(U\)</span> kontrolliert, verzerrt geschätzt wird. Wie stark die Verzerrung ist, hängt von den Eigenschaften des DGP ab. Simulation kann hilfreich sein, um die Verzerrung eines Schätzers in Abhängigkeit der Parameter des DGP zu untersuchen.</p>
<div class="cell" data-fig-width="6" data-fig-height="4" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-simconf" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simconf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<svg width="576" height="384" viewbox="0.00 0.00 476.01 200.12" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 196.12)">
<title>CONFSIM</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-196.12 472.01,-196.12 472.01,4 -4,4"></polygon>
<!-- X -->
<g id="node1" class="node">
<title>X</title>
<ellipse fill="none" stroke="black" cx="18.01" cy="-30.11" rx="18.02" ry="18.02"></ellipse>
<text text-anchor="middle" x="18.01" y="-25.91" font-family="Helvetica,Arial,sans-serif" font-size="14.00">X</text>
</g>
<!-- Y -->
<g id="node2" class="node">
<title>Y</title>
<ellipse fill="none" stroke="black" cx="306.01" cy="-30.11" rx="18.02" ry="18.02"></ellipse>
<text text-anchor="middle" x="306.01" y="-25.91" font-family="Helvetica,Arial,sans-serif" font-size="14.00">Y</text>
</g>
<!-- X&#45;&gt;Y -->
<g id="edge3" class="edge">
<title>X-&gt;Y</title>
<path fill="none" stroke="black" d="M36.03,-30.11C84.6,-30.11 218.57,-30.11 277.53,-30.11"></path>
<polygon fill="black" stroke="black" points="277.63,-33.61 287.63,-30.11 277.63,-26.61 277.63,-33.61"></polygon>
<text text-anchor="middle" x="164.53" y="-4.2" font-family="Helvetica,Arial,sans-serif" font-size="14.00">beta = 2</text>
</g>
<!-- U -->
<g id="node3" class="node">
<title>U</title>
<ellipse fill="none" stroke="gray" cx="162.01" cy="-174.11" rx="18.02" ry="18.02"></ellipse>
<text text-anchor="middle" x="162.01" y="-169.91" font-family="Helvetica,Arial,sans-serif" font-size="14.00" fill="gray">U</text>
</g>
<!-- U&#45;&gt;X -->
<g id="edge2" class="edge">
<title>U-&gt;X</title>
<path fill="none" stroke="gray" stroke-dasharray="5,2" d="M149.23,-161.33C124.21,-136.31 68.57,-80.67 38.4,-50.5"></path>
<polygon fill="gray" stroke="gray" points="40.51,-47.66 30.97,-43.06 35.56,-52.61 40.51,-47.66"></polygon>
<text text-anchor="middle" x="77.91" y="-127.16" font-family="Helvetica,Arial,sans-serif" font-size="14.00">beta = 1</text>
</g>
<!-- U&#45;&gt;Y -->
<g id="edge1" class="edge">
<title>U-&gt;Y</title>
<path fill="none" stroke="gray" stroke-dasharray="5,2" d="M174.79,-161.33C199.81,-136.31 255.45,-80.67 285.62,-50.5"></path>
<polygon fill="gray" stroke="gray" points="288.46,-52.61 293.05,-43.06 283.51,-47.66 288.46,-52.61"></polygon>
<text text-anchor="middle" x="246.11" y="-127.16" font-family="Helvetica,Arial,sans-serif" font-size="14.00">beta = -1</text>
</g>
<!-- e -->
<g id="node4" class="node">
<title>e</title>
<ellipse fill="none" stroke="gray" cx="450.01" cy="-30.11" rx="18" ry="18"></ellipse>
<text text-anchor="middle" x="450.01" y="-25.91" font-family="Helvetica,Arial,sans-serif" font-size="14.00" fill="gray">e</text>
</g>
<!-- e&#45;&gt;Y -->
<g id="edge4" class="edge">
<title>e-&gt;Y</title>
<path fill="none" stroke="gray" stroke-dasharray="5,2" d="M431.77,-30.11C407.21,-30.11 363.26,-30.11 334.36,-30.11"></path>
<polygon fill="gray" stroke="gray" points="334.1,-26.61 324.1,-30.11 334.1,-33.61 334.1,-26.61"></polygon>
</g>
</g>
</svg>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simconf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;5.1: DGP mit unbeobachtbarem Confounder U
</figcaption>
</figure>
</div>
</div>
</div>
<p>Für die Simulation von Stichproben gemäß <a href="#fig-simconf" class="quarto-xref">Abbildung&nbsp;<span>5.1</span></a> nutzen wir den linearen Prozess</p>
<p><span class="math display">\[\begin{align*}
  X =&amp; \, a + \alpha_1 U,\\
  Y =&amp; \, \beta_1 X + \beta_2 U + e,
\end{align*}\]</span></p>
<p>mit <span class="math inline">\(a \sim \mathcal{U}[0,1]\)</span>, <span class="math inline">\(U\sim N(0, 2^2)\)</span> und <span class="math inline">\(e\sim N(0, 10)\)</span> und wählen die Parameter <span class="math inline">\(\alpha_1 = 1\)</span>, <span class="math inline">\(\beta_1 = 2\)</span> und <span class="math inline">\(\beta_2 = -1\)</span>.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> Der nächste Code-Block implementiert den DGP und zeigt die KQ-Schätzung des fehlspezifizierten Modells</p>
<p><span class="math display">\[\begin{align*}
  Y = \beta_1 X + \epsilon
\end{align*}\]</span></p>
<p>anhand einer simulierten Stichprobe mit einem Umfang von 100 Beobachtungen.</p>
<pre class="{webr-r}"><code>#| autorun: true

# Parameter
n &lt;- 100
alpha_1 &lt;- 1
beta_1 &lt;- 2
beta_2 &lt;- -.25

set.seed(1234)

# Stichprobe ziehen
dat &lt;- tibble(
    U = rnorm(n, 0, 2),
    X = alpha_1 * U + runif(n, 0, 1),
    Y = beta_1 * X + beta_2 * U + rnorm(n, 10)
) 

# Fehlspezifiziertes Modell schätzen
lm(
  formula = Y ~ X - 1, 
  data = dat
) %&gt;% 
  summary()</code></pre>
<p>Analog zu <a href="#sec-simspv" class="quarto-xref"><span>Kapitel 5.1</span></a> ist diese Simulation mit nur einer Iteration wenig aussagekräftig für die Verzerrung der KQ-Schätzers. Für eine ausführlichere Analyse implementieren wir zunächst beide Schritte der Simulation (Stichprobe generieren, Modell schätzen) in einer Funktion <code>sim_function_conf()</code>, der wir sämtliche Parameter sowie das zu schätzende Regressionsmodell als Fomel übergeben können. Diese Funktion gibt die aus dem <code>lm</code>-Objekt ausgelesene KQ-Schätzung von <span class="math inline">\(\beta_1\)</span> zurück. Wir testen die Funktion <code>sim_function_conf()</code> durch Verwendung des selben Seeds.</p>
<pre class="{webr-r}"><code>#| autorun: true
# Funktion für Simulation definieren
sim_function_conf &lt;- function(n, alpha_1, beta_1, beta_2, formula) {
  
  # Simulieren
  tibble(
    U = rnorm(n, 0, 2),
    X = alpha_1 * U + runif(n, 0, 1),
    Y = beta_1 * X + beta_2 * U + rnorm(n, 10)
  ) %&gt;% 
    # KQ-Schätzung
    lm(
      formula = as.formula(formula), 
      data = .
    ) %&gt;%
      # Schätzwert auslesen
      coefficients() %&gt;% 
      .["X"]    
  
}

# Seed wie zuvor
set.seed(1234)

# Test
sim_function_conf(
  n = 100, 
  alpha = 1, 
  beta_1 = 2, 
  beta_2 = -.25, 
  formula = "Y ~ X - 1"
)</code></pre>
<p>Der mit <code>sim_function_conf()</code> simulierte Zug aus der Stichprobenverteilung stimmt mit dem Ergebnis des vorherigen Zufallsexperiments überein. Wir können nun die Simulation durch iterative Berechnung von <code>sim_function_conf()</code> über die Indexmenge <code>1:N</code> durchführen. Wie zuvor visualisieren wir die Simulationsergebnisse mit einem Plot der geschätzten Dichtefunktion von <span class="math inline">\(\widehat{\beta}_1\)</span>.</p>
<pre class="{webr-r}"><code>#| autorun: true

# Parameter
n &lt;- 100
N &lt;- 1000
alpha_1 &lt;- 1
beta_1 &lt;- 2
beta_2 &lt;- -.25

# Simulation durchführen
sim_est &lt;- tibble(
  hatbeta_1 = map_dbl(
    .x = 1:N,
    .f =  ~ sim_function_conf(
      n = n, 
      alpha_1 = alpha_1 ,
      beta_1 = beta_1,
      beta_2 = beta_2 ,
      formula = "Y ~ X - 1"
    )
  )
)

# Gesch. Stichprobenverteilung plotten
ggplot(
  data = sim_est, 
  mapping = aes(x = hatbeta_1)
  ) +
  # gesch. Dichtefunktion
  geom_density() +
  # Effekt einzeichnen
  geom_vline(
    xintercept = beta_1, 
    linetype = "dashed",
    col = "red"
  ) +
  labs(title = "Verzerrte Schätzung durch Confounder") +
  theme_cowplot()</code></pre>
<p>Der grafische Vergleich der simulierten Stichprobenverteilung von <span class="math inline">\(\widehat{\beta}_1\)</span> mit dem wahren Koeffizienten <span class="math inline">\(\beta_1 = 2\)</span> (gestrichelte rote Linie) zeigt, dass <span class="math inline">\(\widehat{\beta}_1\)</span> aufgrund des ausgelassenen Confounders <span class="math inline">\(U\)</span> für die hier gewählte Spezifikation des DGP tatsächlich ein <em>verzerrter</em> Schätzer für den kausalen Effekt <span class="math inline">\(\beta_1\)</span> ist: Die geschätzte Dichtefunktion ist ein Indikator dafür, dass die Verteilungsfunktion von <span class="math inline">\(\widehat{\beta}_1\)</span> einen Großteil der Wahrscheinlichkeitsmasse im Wertebereich oberhalb von <span class="math inline">\(\beta_1 = 2\)</span> hat, sodass wir den kausalen Effekt im Mittel <em>überschätzen</em>.</p>
<p>Wir können die Simulationsergebnisse in <code>sim_est</code> nutzen, um die Verzerrung<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> von <span class="math inline">\(\widehat\beta_1\)</span> zu schätzen.</p>
<pre class="{webr-r}"><code>#| autorun: true
# Verzerrung des KQ-Schätzers schätzen
mean(sim_est$hatbeta_1) - beta_1</code></pre>
<p>Diese Berechnung anhand von Zügen aus der Stichprobenverteilung von <span class="math inline">\(\widehat{\beta}_1\)</span> zeigt eine deutliche positive Verzerrung des KQ-Schätzers von <span class="math inline">\(\beta_1\)</span> aufgrund des Confounders <span class="math inline">\(U\)</span> von etwa 0.94.</p>
<p>Anhand von <code>sim_function_conf()</code> können wir die Identifizierbarkeit des kausalen Effekts <span class="math inline">\(\beta_1\)</span> bei Kontrolle für <span class="math inline">\(U\)</span> im Modell</p>
<p><span class="math display">\[\begin{align*}
  Y = \beta_0 + \beta_1 X + \beta_2 U + \varepsilon
\end{align*}\]</span></p>
<p>überprüfen, in dem wir die Simulation unter Angabe dieses Modells über das Argument <code>formula</code> durchführen.</p>
<pre class="{webr-r}"><code>#| autorun: true

# Parameter
n &lt;- 100
N &lt;- 1000
alpha_1 &lt;- 1
beta_1 &lt;- 2
beta_2 &lt;- -.25

# Simulation durchführen
sim_est &lt;- tibble(
  hatbeta_1 = map_dbl(
    .x = 1:N,
    .f =  ~ sim_function_conf(
      n = n, 
      alpha_1 = alpha_1,
      beta_1 = beta_1,
      beta_2 = beta_2 ,
      # Kontrolle für Confounder U
      formula = "Y ~ X + U"
    )
  )
)

# Gesch. Stichprobenverteilung plotten
ggplot(
  data = sim_est, 
  mapping = aes(x = hatbeta_1)
) +
  geom_density() +
  geom_vline(
    xintercept = beta_1, 
    linetype = "dashed",
    col = "red"
  ) +
  labs(title = "Erwartungstreue bei multipler Regression") +
  theme_cowplot()</code></pre>
<p>Die geschätzte Stichprobenverteilung von <span class="math inline">\(\widehat{\beta}_1\)</span> bei Kontrolle für den Confounder <span class="math inline">\(U\)</span> zeigt keine Anzeichen für eine Verzerrung des Schätzers für den kausalen Effekt von <span class="math inline">\(X\)</span> auf <span class="math inline">\(Y\)</span>. Die Monte-Carlo-Schätzung der Verzerrung von <span class="math inline">\(\widehat{\beta}_1\)</span> unterstützt das Ergebnis der grafischen Analyse.</p>
<pre class="{webr-r}"><code>#| autorun: true
# Verzerrung des KQ-Schätzers schätzen
mean(sim_est$hatbeta_1) - beta_1</code></pre>
</section>
<section id="regression-verzerrung-durch-collider" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="regression-verzerrung-durch-collider"><span class="header-section-number">5.1.3</span> Regression: Verzerrung durch Collider</h3>
<p>Der Graph in <a href="#fig-simcol" class="quarto-xref">Abbildung&nbsp;<span>5.2</span></a> zeigt einen DGP, bei dem die Variable <span class="math inline">\(C\)</span> ein <em>Collider</em> auf dem Pfad <span class="math inline">\(X\rightarrow C \leftarrow Y\)</span> ist. Für die Identifikation des Effekts von <span class="math inline">\(X\)</span> auf <span class="math inline">\(Y\)</span> ist <span class="math inline">\(C\)</span> damit eine irrelavante Variable, für die <em>nicht</em> kontrolliert werden darf: Statistische Verfahren, die den Effekt von <span class="math inline">\(X\)</span> auf <span class="math inline">\(Y\)</span> unter Kontrolle des Effekts von <span class="math inline">\(C\)</span> auf <span class="math inline">\(Y\)</span> schätzen sind verzerrt, weil ein Backdoor-Pfad durch <span class="math inline">\(C\)</span> besteht.</p>
<div class="cell" data-fig-width="6" data-fig-height="4" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-simcol" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simcol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<svg width="576" height="384" viewbox="0.00 0.00 476.01 200.11" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 196.11)">
<title>COLSIM</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-196.11 472.01,-196.11 472.01,4 -4,4"></polygon>
<!-- X -->
<g id="node1" class="node">
<title>X</title>
<ellipse fill="none" stroke="black" cx="18.01" cy="-30.11" rx="18.02" ry="18.02"></ellipse>
<text text-anchor="middle" x="18.01" y="-25.91" font-family="Helvetica,Arial,sans-serif" font-size="14.00">X</text>
</g>
<!-- Y -->
<g id="node2" class="node">
<title>Y</title>
<ellipse fill="none" stroke="black" cx="306.01" cy="-30.11" rx="18.02" ry="18.02"></ellipse>
<text text-anchor="middle" x="306.01" y="-25.91" font-family="Helvetica,Arial,sans-serif" font-size="14.00">Y</text>
</g>
<!-- X&#45;&gt;Y -->
<g id="edge3" class="edge">
<title>X-&gt;Y</title>
<path fill="none" stroke="black" d="M36.03,-30.11C84.6,-30.11 218.57,-30.11 277.53,-30.11"></path>
<polygon fill="black" stroke="black" points="277.63,-33.61 287.63,-30.11 277.63,-26.61 277.63,-33.61"></polygon>
<text text-anchor="middle" x="164.53" y="-4.2" font-family="Helvetica,Arial,sans-serif" font-size="14.00">beta_1 = 2</text>
</g>
<!-- C -->
<g id="node3" class="node">
<title>C</title>
<ellipse fill="none" stroke="black" cx="162.01" cy="-174.11" rx="18" ry="18"></ellipse>
<text text-anchor="middle" x="162.01" y="-169.91" font-family="Helvetica,Arial,sans-serif" font-size="14.00">C</text>
</g>
<!-- X&#45;&gt;C -->
<g id="edge2" class="edge">
<title>X-&gt;C</title>
<path fill="none" stroke="black" d="M30.79,-42.89C55.81,-67.91 111.45,-123.54 141.62,-153.71"></path>
<polygon fill="black" stroke="black" points="139.51,-156.55 149.05,-161.15 144.46,-151.6 139.51,-156.55"></polygon>
<text text-anchor="middle" x="102.11" y="-68.65" font-family="Helvetica,Arial,sans-serif" font-size="14.00">beta = .25</text>
</g>
<!-- Y&#45;&gt;C -->
<g id="edge1" class="edge">
<title>Y-&gt;C</title>
<path fill="none" stroke="black" d="M293.23,-42.89C268.21,-67.91 212.57,-123.54 182.4,-153.71"></path>
<polygon fill="black" stroke="black" points="179.56,-151.6 174.97,-161.15 184.51,-156.55 179.56,-151.6"></polygon>
<text text-anchor="middle" x="221.91" y="-68.65" font-family="Helvetica,Arial,sans-serif" font-size="14.00">beta = .25</text>
</g>
<!-- e -->
<g id="node4" class="node">
<title>e</title>
<ellipse fill="none" stroke="gray" cx="450.01" cy="-30.11" rx="18" ry="18"></ellipse>
<text text-anchor="middle" x="450.01" y="-25.91" font-family="Helvetica,Arial,sans-serif" font-size="14.00" fill="gray">e</text>
</g>
<!-- e&#45;&gt;Y -->
<g id="edge4" class="edge">
<title>e-&gt;Y</title>
<path fill="none" stroke="gray" stroke-dasharray="5,2" d="M431.77,-30.11C407.21,-30.11 363.26,-30.11 334.36,-30.11"></path>
<polygon fill="gray" stroke="gray" points="334.1,-26.61 324.1,-30.11 334.1,-33.61 334.1,-26.61"></polygon>
</g>
</g>
</svg>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simcol-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;5.2: DGP mit Collider-Variable C
</figcaption>
</figure>
</div>
</div>
</div>
<p>Ähnlich wie in <a href="#sec-simbiasconf" class="quarto-xref"><span>Kapitel 5.1.2</span></a> können wir die Konsequezen der Kontrolle für eine Collider-Variable in einem linearen Regressionsmodell anhand einer Simulationsstudie untersuchen. Wir implementieren hierzu den DGP</p>
<p><span class="math display">\[\begin{align*}
  X \sim&amp; \, N(0,1),\\
  Y =&amp; \, \beta_1 X + e,\\
  C =&amp; \, N(0,1) + .25X + .25Y,
\end{align*}\]</span> wobei <span class="math inline">\(e \sim N(0,3^2)\)</span> erneut ein unsystematischer Fehlterterm für <span class="math inline">\(Y\)</span> ist. Wie im DGP aus <a href="#sec-simbiasconf" class="quarto-xref"><span>Kapitel 5.1.2</span></a> wählen wir <span class="math inline">\(\beta_1 = 2\)</span> für den wahren kausalen Effekt von <span class="math inline">\(X\)</span> auf <span class="math inline">\(Y\)</span>.</p>
<pre class="{webr-r}"><code>#| autorun: true
# Simulationsfunktion: DGP mit Collider
sim_function_col &lt;- function(n, beta_1, formula) {
    # Daten erzeugen
    tibble(
        X = rnorm(n),
        Y = beta_1 * X + rnorm(n, sd = 3),
        C = .25 * X + .25 * Y + rnorm(n)
    ) %&gt;% 
        # Modell schätzen
        lm(
            formula = as.formula(formula), 
            data = .
        ) %&gt;% 
        # Koeffizientenschätzung auslesen
        coefficients() %&gt;% 
        .["X"]    
}</code></pre>
<p>In der nachfolgenden Simulation iterieren wir <code>sim_function_col()</code> für zwei verschiedene Modelle und speichern Ergebnisse in einer <code>tibble</code>: Die erste Spalte von <code>sim_est_col</code> enthält simulierte KQ-Schätzungen von <span class="math inline">\(\widehat{\beta}_1\)</span> in einem einfachen Regressionsmodell, dass <em>nicht</em> für den Collider <span class="math inline">\(C\)</span> kontrolliert (<code>formula = "Y ~ X"</code>). Die zweite Spalte hingegen sammelt Schätzungen für ein multiples Modell mit Kontrolle für <span class="math inline">\(C\)</span> (<code>formula = "Y ~ X + C"</code>).</p>
<pre class="{webr-r}"><code>#| autorun: true
# Parameter
n &lt;- 150
N &lt;- 1000
beta_1 = 2

sim_est_col &lt;- tibble(
    # Ohne Kontrolle für C
    hatbeta_1 = map_dbl(
        .x = 1:N,
        .f =  ~ sim_function_col(
            n = n, 
            beta_1 = beta_1,
            formula = "Y ~ X"
        )
    ),
    # Kontrolle für C
    hatbeta_1_C = map_dbl(
        .x = 1:N, 
        .f = ~ sim_function_col(
            n = n, 
            beta_1 = beta_1,
            formula = "Y ~ X + C"
        )
    )
)

# Überblick
head(sim_est_col)</code></pre>
<p>Für die Auswertung der Simulationsergebnisse hinsichtlich der Konsequenzen der Kontrolle für den Collider <span class="math inline">\(C\)</span> plotten wir die geschätzen Dichtefunktionen für die Stichprobenverteilung von <span class="math inline">\(\widehat{\beta}_1\)</span> aus beiden Monte-Carlo-Experimenten gemeinsam und vergleich mit dem wahren Wert <span class="math inline">\(\beta_1 = 2\)</span>.</p>
<pre class="{webr-r}"><code>#| autorun: true
# Vergleich von simulieren Stichprobenverteilungen 
# in Regressionen mit und ohne Collider
ggplot(data = sim_est_col) +
  geom_density(
    mapping = aes(x = hatbeta_1, linetype = "Y ~ X"),
  ) +
  geom_density(
    mapping = aes(x = hatbeta_1_C, linetype = "Y ~ X + C"), 
  ) +
  geom_vline(
    xintercept = beta_1, 
    linetype = "dashed",
    col = "red"
  ) +
  scale_linetype_manual(
    "Modell",
    values = c(
      "Y ~ X" = "solid", 
      "Y ~ X + C" = "dotdash"
    )
  ) +
  labs(title = "Simulation von Collider-Bias in linearer Regression") +
  theme_cowplot() + 
  theme(legend.position = "top")</code></pre>
<p>Die Abbildung zeigt deutlich die (negative) Verzerrung des KQ-Schätzers für den interessierenden kausalen Effekt im Modell mit Kontrolle für den Collider <span class="math inline">\(C\)</span>. Die Simulationsergebnisse für eine einfache Regression von <span class="math inline">\(Y\)</span> auf <span class="math inline">\(X\)</span> hingegen stimmen mit dem theretischen Resultat überein, dass der KQ-Schätzer für <span class="math inline">\(\beta_1\)</span> in diesem Modell erwartungstreu ist.</p>
<p>Durch Zusammenfassung der Simulationsergebnisse mit <code>dplyr::summarize()</code> können wir den Collider-Bias im Modell mit Kontrolle für <span class="math inline">\(C\)</span> schätzen und die Unverzerrtheit von <span class="math inline">\(\widehat{\beta}_1\)</span> in der einfachen Regression von <span class="math inline">\(Y\)</span> auf <span class="math inline">\(X\)</span> prüfen.</p>
<pre class="{webr-r}"><code>#| autorun: true
# Bias aus Simulationsergebnissen schätzen
sim_est_col %&gt;%
  summarise(
    bias_simple = mean(hatbeta_1) - beta_1,
    bias_collider = mean(hatbeta_1_C) - beta_1
  )</code></pre>
</section>
</section>
<section id="regression-durchschnittlicher-behandlungseffekt" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="regression-durchschnittlicher-behandlungseffekt"><span class="header-section-number">5.2</span> Regression: Durchschnittlicher Behandlungseffekt</h2>
<p>Wir können Simulation einsetzen, um die Güte der Schätzung von Behandlungseffekten in linearen Regressionsmodellen zu untersuchen. Hierzu implementieren wir einen DGP gemäß <a href="#fig-simheteff" class="quarto-xref">Abbildung&nbsp;<span>5.3</span></a>.</p>
<div class="cell" data-fig-width="5" data-fig-height="3" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-simheteff" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-simheteff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<svg width="480" height="288" viewbox="0.00 0.00 396.00 252.02" xmlns="http://www.w3.org/2000/svg" xlink="http://www.w3.org/1999/xlink" style="; max-width: none; max-height: none">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(36 216.02)">
<title>HETEFFSIM</title>
<polygon fill="white" stroke="transparent" points="-36,36 -36,-216.02 360,-216.02 360,36 -36,36"></polygon>
<!-- B -->
<g id="node1" class="node">
<title>B</title>
<ellipse fill="none" stroke="black" cx="18" cy="-18.01" rx="18" ry="18"></ellipse>
<text text-anchor="middle" x="18" y="-13.81" font-family="Helvetica,Arial,sans-serif" font-size="14.00">B</text>
</g>
<!-- Y -->
<g id="node2" class="node">
<title>Y</title>
<ellipse fill="none" stroke="black" cx="162" cy="-18.01" rx="18.02" ry="18.02"></ellipse>
<text text-anchor="middle" x="162" y="-13.81" font-family="Helvetica,Arial,sans-serif" font-size="14.00">Y</text>
</g>
<!-- B&#45;&gt;Y -->
<g id="edge1" class="edge">
<title>B-&gt;Y</title>
<path fill="none" stroke="black" d="M36.24,-18.01C60.8,-18.01 104.75,-18.01 133.65,-18.01"></path>
<polygon fill="black" stroke="black" points="133.91,-21.51 143.91,-18.01 133.91,-14.51 133.91,-21.51"></polygon>
<text text-anchor="middle" x="84.94" y="-5.41" font-family="Helvetica,Arial,sans-serif" font-size="14.00">β_1 heterogen</text>
</g>
<!-- X -->
<g id="node3" class="node">
<title>X</title>
<ellipse fill="none" stroke="black" cx="162" cy="-162.01" rx="18.02" ry="18.02"></ellipse>
<text text-anchor="middle" x="162" y="-157.81" font-family="Helvetica,Arial,sans-serif" font-size="14.00">X</text>
</g>
<!-- X&#45;&gt;Y -->
<g id="edge2" class="edge">
<title>X-&gt;Y</title>
<path fill="none" stroke="black" d="M162,-143.77C162,-119.21 162,-75.26 162,-46.36"></path>
<polygon fill="black" stroke="black" points="165.5,-46.1 162,-36.1 158.5,-46.1 165.5,-46.1"></polygon>
<text text-anchor="middle" x="191.58" y="-95.34" font-family="Helvetica,Arial,sans-serif" font-size="14.00">β_2 = 2</text>
</g>
<!-- e -->
<g id="node4" class="node">
<title>e</title>
<ellipse fill="none" stroke="gray" cx="306" cy="-18.01" rx="18" ry="18"></ellipse>
<text text-anchor="middle" x="306" y="-13.81" font-family="Helvetica,Arial,sans-serif" font-size="14.00" fill="gray">e</text>
</g>
<!-- e&#45;&gt;Y -->
<g id="edge3" class="edge">
<title>e-&gt;Y</title>
<path fill="none" stroke="gray" stroke-dasharray="5,2" d="M287.76,-18.01C263.2,-18.01 219.25,-18.01 190.35,-18.01"></path>
<polygon fill="gray" stroke="gray" points="190.09,-14.51 180.09,-18.01 190.09,-21.51 190.09,-14.51"></polygon>
</g>
</g>
</svg>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simheteff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;5.3: DGP mit heterogenen Behandlungseffekten
</figcaption>
</figure>
</div>
</div>
</div>
<p>Für die Komponenten wählen wir: <span class="math display">\[\begin{align}
  \begin{split}
    \text{B} &amp;\sim \text{Bernoulli}(0.5) \\
    X &amp;\sim N(0, 2) \\
    \beta_1 &amp;\sim \mathcal{U}(0, 3) \\
    e &amp;\sim N(0, 2) \\
    \\
    Y &amp;= 1 + \beta_1 \cdot \text{B} + 2 \cdot X + e
  \end{split}\label{eq:dgpatesim}
\end{align}\]</span></p>
<p>In diesem linearen DGP bestimmt <span class="math inline">\(B\)</span> über die Zuteilung der Behandlung. <span class="math inline">\(X\)</span> ist eine Determinante der Outcome-Variable <span class="math inline">\(Y\)</span> ohne Backdoor-Pfad. Der Behandlungseffekt <span class="math inline">\(\beta_1\)</span> ist <em>heterogen</em>, da <span class="math inline">\(\beta_1\)</span> aus einer kontinuierlichen Gleichverteilung auf dem Intervall <span class="math inline">\([0, 3]\)</span> gezogen wird. Der durchschnittliche Behandlungseffekt (ATE) entspricht hier dem <em>Erwartungswert</em> von <span class="math inline">\(\beta_1\)</span>, was zu einem ATE von 1.5 führt, da</p>
<p><span class="math display">\[\begin{align*}
  \textup{ATE} =&amp;\, \textup{E}(\beta_1)\\
  =&amp;\, \frac{1}{2}(a + b)\\
  =&amp;\, \frac{1}{2}(0 + 3) = 1.5.
\end{align*}\]</span></p>
<p>Wir verfizieren nachfolgend mit Monte-Carlo-Simulation für Stichproben von DGP <span class="math inline">\(\eqref{eq:dgpatesim}\)</span> mit <span class="math inline">\(n=150\)</span>, dass</p>
<ul>
<li><p>der KQ-Schätzer für <span class="math inline">\(\beta_1\)</span> im Modell <span class="math inline">\(Y=\beta_0 + \beta_1 B + \epsilon\)</span> ein erwartungstreuer Schätzer für den ATE ist und</p></li>
<li><p>kontrollieren für <span class="math inline">\(X\)</span> hier die Präzision der Schätzung des ATE verbessert.</p></li>
</ul>
<p>Im nachfolgenden Code-Block erzeugen wir die Simulationsergebnisse in jeder Iteration durch Berechnung der interessierenen Schätzer auf derselben simulierten Stichprobe und geben die Ergebnisse als <code>tibble()</code> mit einer Reihe und zwei benannten Einträgen zurück. Die Funktion <code>map_dfr()</code> fasst die Ergebnisse nach der Iteration über <code>1:N</code> als <code>tibble()</code> zusammen. Wir nutzen hier einen Ansatz, bei dem die Schritte für die Simulation dem Argument <code>.f</code> über den Syntax <code>~ { ... }</code> innerhalb einer <em>anonymen Funktion</em> ohne Argumente.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<pre class="{webr-r}"><code>#| autorun: true
# Parameter
n &lt;- 150
N &lt;- 1000

set.seed(1234)

# Iteration mit map_dfr
sim_res_ATE &lt;- map_dfr(
  .x = 1:N, 
  .f = ~ {
    # Datensatz simulieren
    df &lt;- tibble(
      # Behandlungsindikator
      treat = sample(0:1, size = n, replace = TRUE),
      # Determinante von Y
      X = rnorm(n = n, sd = 2), 
      # Heterogener Behandlungseffekt
      TE = runif(n = n, 0, 3),
      # Outcome-Variable
      Y = 1 + TE * treat + 2 * X + rnorm(n = n, sd = 2) 
    )
    
    # ATE mit Regression schätzen
    `Modell ohne Kovariable X` = lm(
      formula = Y ~ treat, 
      data = df
    ) %&gt;%
      coefficients() %&gt;%
      .["treat"]
    
    # Regression mit X
    `Modell mit Kovariable X` = lm(
      formula = Y ~ treat + X, 
      data = df
    ) %&gt;%
      coefficients() %&gt;%
      .["treat"]
    
    return(
      # tibble zurückgeben
      tibble(
        `Modell ohne Kovariable X`,
        `Modell mit Kovariable X`
      )
    )
  }
  
)</code></pre>
<p>Für die grafische Auswertung transformieren wir die Simulationsergebnisse in <code>sim_res_ATE</code> mit <code>pivot_longer()</code> in ein langes Format.</p>
<pre class="{webr-r}"><code>#| autorun: true
# Vergleich simulierter Dichtefunktionen
sim_res_ATE %&gt;%
  pivot_longer(
    cols = everything(),
    names_to = "variable", 
    values_to = "hatbeta_1"
  ) %&gt;%
  
  ggplot(
    mapping = aes(
      x = hatbeta_1, 
      col = variable)
  ) +
  geom_density() +
  # ATE einzeichnen
  geom_vline(
    xintercept = 1.5, 
    linetype = "dashed", 
    col = "red"
  ) +
  scale_color_discrete("KQ-Schätzer im") + 
  theme_cowplot() +
  labs(title = "Präzisere Schätzung mit mutlipler Regression") +
  theme(legend.position = "top")</code></pre>
<p>Die grafische Analyse der Stichprobenverteilungen bestätigt, dass der KQ-Schätzer für <span class="math inline">\(\beta_1\)</span> sowohl im Modell mit Kontrolle für <span class="math inline">\(X\)</span> als auch im Modell ohne <span class="math inline">\(X\)</span> erwartungstreu für den ATE von 1.5 ist. Da <span class="math inline">\(X\)</span> gemäß DGP <span class="math inline">\(\eqref{eq:dgpatesim}\)</span> einen größeren Teil der Variation in <span class="math inline">\(Y\)</span> verursacht, verbesserte Kontrolle für <span class="math inline">\(X\)</span> hier die Präzision der Schätzung des ATE mit KQ.</p>
<p>Die Variabilität der Ansätze können wir durch Zusammenfassung der Spalten in <code>sim_res_ATE</code> mit <code>summarize()</code> und <code>across()</code> quantifizieren, wobei wir <code>sd</code> als zusammenfassende Statistik nutzen und <code>.names = "sd_{.col}"</code> ein entsprechendes Präfix für die Variablennamen einführt.</p>
<pre class="{webr-r}"><code>#| autorun: true
# Standardabweichung der Schätzungen
sim_res_ATE %&gt;% 
  summarise(
    across(
      .cols = everything(), 
      .fns = sd,
      .names = "sd_{.col}"
    )
  )</code></pre>
</section>
<section id="verletzung-von-modellannahmen-heteroskedastizität" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="verletzung-von-modellannahmen-heteroskedastizität"><span class="header-section-number">5.3</span> Verletzung von Modellannahmen: Heteroskedastizität</h2>
<p>Unter der Annahme von <em>Homoskedastizität</em> (konstante Varianz) der Fehlerterme des Modells ist die KQ-Schätzung von Behandlungseffekten anhand linearer Regression effizient, d.h. der KQ-Schätzer hat die geringste Varianz unter allen unverzerrten Schätzern des interessierenden Koeffizienten.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> Hängt die Varianz der Fehlerterme von den Regressoren ab, liegt <em>Heteroskedastizität</em> vor: Die Fehlerterm-Varianz unterscheided sich zwischen den Beobachtungen, in Abhängigkeit der Ausprägungen der Regressoren. Unter Heteroskedastie ist der KQ-Schätzer nicht länger der effizienteste Schätzer: In Verfahren wie der gewichteten KQ-Methode (WKQ)<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> haben Beobachtungen mit geringer Fehlerterm-Varianz einen größeren Einfluss als Beobachtungen mit großer Varianz, sodass der WKQ-Schätzer präziser als der KQ-Schätzer sein kann.</p>
<p>Weiterhin sind bei heteroskedastischen Fehlertermen die (aus historischen Gründen) standardmäßig von <code>summary()</code> berechneten Standardfehler <em>ungültig</em>, und können die Unsicherheit von KQ unterschätzen. Dies ist problematisch, da unter Verwendung von ungültigen Standardfehlern berechnete Inferenzsstatistiken ebenfalls ungültig sind. Als Konsequenz erhöht sich die Gefahr falscher Schlussfolgerungen hinsichtlich des zu schätzenden Behandlungseffekts anhand von Test-Statistiken und Konfidenzintervallen.</p>
<p>Wir zeigen nachfolgend, wie die Konsequenzen von Heteroskedastizität für den KQ-Schätzer mit Simulation untersucht werden können. Hierfür betrachten wir den DGP</p>
<p><span class="math display">\[\begin{align}
  \begin{split}
    X \sim&amp;\, \chi^2_{50}\\
    e \sim&amp;\, N(0, \sigma_e^2(X))\\
    Y =&amp;\, \beta_1 X + e,
  \end{split}\label{eq:simhetdgp}
\end{align}\]</span></p>
<p>wobei die Fehlerterm-Varianz <span class="math inline">\(\sigma_e^2(X)\)</span> eine Funktion von <span class="math inline">\(X\)</span> ist, <span class="math display">\[\begin{align*}
  \sigma_e^2(X) = \textup{Var}(e\vert X) = \lvert X-50 \rvert^{p}.
\end{align*}\]</span> Der Parameter <span class="math inline">\(p\)</span> bestimmt die funktionale Form dieser bedingten Varianz.</p>
<p>Der nächste Code-Chunk plottet die Funktion <span class="math inline">\(f(x) = \lvert X-50 \rvert^{p}\)</span> für verschiedene <span class="math inline">\(p\)</span> über den Wertebereich von <span class="math inline">\(X\)</span>. Hierfür berechnen wir <span class="math inline">\(f(x)\)</span> für ein mit <code>expand_grid()</code> erstelltes Raster von Werten für <span class="math inline">\(X\)</span> und <span class="math inline">\(p\)</span>.</p>
<pre class="{webr-r}"><code>#| autorun: true
# Raster erstellen, f(x) berechnen
df &lt;- expand_grid(
  x = seq(30, 70, by = 0.1), 
  p = c(0, 1, 1.5, 1.75),
  ) %&gt;% 
  mutate(y = abs(x - 50)^p)

# Funktionen plotten
ggplot(
  data = df,
  mapping =  aes(x = x, y = y, color = factor(p))
) +
  geom_line() +
  labs(
    title = "Plot von |x-50|^p für verschiedene p",
    y = "|x-50|^p "
  ) +
  scale_color_discrete(name = "p") +
  theme_cowplot() +
  theme(legend.position = "top")</code></pre>
<p>Für die Simulation heteroskedastischer Daten mit <span class="math inline">\(\eqref{eq:simhetdgp}\)</span> verwenden wir <span class="math inline">\(p = 1.5\)</span> und <span class="math inline">\(\beta_1 = 0\)</span> (kein Effekt). Die nachfolgende Grafik zeigt eine simulierte Stichprobe mit 150 Beobachtungen.</p>
<pre class="{webr-r}"><code>#| autorun: true
n &lt;- 150

# Daten erzeugen
df_het &lt;- tibble(
  # Regressor
  X = rchisq(n = n, df = 50),
  # Heteroskedastische Fehler
  e = abs(X - 50)^(1.5) * rnorm(n),
  # Outcome-Variable
  Y = e
)

# Punkteplot
ggplot(
  data = df_het, 
  mapping = aes(x = X, y = Y)
) +
  geom_point(col = "steelblue", alpha = .75) +
  labs(title = "Heteroskedastische Daten") +
  theme_cowplot()</code></pre>
<p>In den Simulationsdurchläufen schätzen wir jeweils <span class="math inline">\(\beta_1\)</span> im Modell <span class="math inline">\(Y=\beta_1X+\epsilon\)</span> mit KQ, berechnen den nur bei Homoskedastie gültigen Standardfehler und eine bei Heteroskedastie robuste Schätzung. Für lezteres verwenden wir <code>sandwich::vcovHC()</code> und mit <code>type = "HC1"</code>.<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> Wir fassen diese Schritte in der Funktion <code>sim_function_het()</code> zusammen.</p>
<pre class="{webr-r}"><code>#| autorun: true
sim_function_het &lt;- function(n, p) {  
  
  # Regressor
  X &lt;- rchisq(n = n, df = 50)
  # Heteroskedastische Fehler
  e &lt;- abs(X - 50)^(1.5) * rnorm(n, mean = 0, sd = 1)
  # Outcome-Variable
  Y &lt;- e

  # Modell schätzen
  model &lt;- lm(Y ~ X - 1)
  
  # HC0-Standardfehler mit summary()
  s &lt;- summary(model)
  
  # Wurzel(rob Varianz-Schätzer) = robuster SE
  sw &lt;- sqrt(
    sandwich::vcovHC(model, type = "HC1")
  )
  
  # WKQ
  # Gewichte
  residuals &lt;- resid(model)
  weights &lt;- 1 / (residuals^2)

  # WKQ-Schätzung
  wkq_model &lt;- lm(
    formula = Y ~ X - 1,
    weights = weights
  )
  
  tibble(
    # Koeffizientenschätzung
    beta = s$coefficients["X", 1],
    # WKQ-Schätzer
    beta_wkq = wkq_model$coefficients["X"],
    # HC0-Standardfehler
    se = s$coefficients["X", 2],
    # HC1-Standardfehler
    se_rob = sw
  )

}</code></pre>
<pre class="{webr-r}"><code>#| autorun: true
# Parameter
N &lt;- 1000
n &lt;- 150
p &lt;- 1.5

set.seed(1234)

# Simulation durchführen
sim_res_het = map_dfr(
  .x = 1:N,
  .f = ~ sim_function_het(n = n, p)
)

# Überblick
head(sim_res_het)</code></pre>
<pre class="{webr-r}"><code>#| autorun: true
# Standardabweichung der Stichprobenverteilung
sd(sim_res_het$beta)

# Von summary() berechneter Standardfehler
mean(sim_res_het$se)

# Robuster Standardfehler
mean(sim_res_het$se_rob)</code></pre>
<p>Die quantitative Auswertung der Ergebnisse deuten darauf hin, dass der nur bei Homoskedastie gültige Standardfehler die Standardabweichung von <span class="math inline">\(\widehat{\beta}_1\)</span> deutlich unterschätzt. Der anhand der Simulationsergebnisse geschätzte Erwartungswert des robusten Standardfehlers hingegen liegt nahe bei der Standardabweichung der simulierten Stichprobenverteilung von <span class="math inline">\(\widehat{\beta}_1\)</span>. Die Tendenz des nur bei Homoskedastie gültigen Standardfehlers, kleinere Schätzungen der Unsicherheit von <span class="math inline">\(\widehat{\beta}_1\)</span> zu liefern, können wir anhand der geschätzten Dichtefunktionen für <code>se</code> und <code>se_rob</code> grafisch zeigen.</p>
<pre class="{webr-r}"><code>#| autorun: true
ggplot(data = sim_res_het) +
  geom_density(mapping = aes(x = se, linetype = "Nicht robust")) +
  geom_density(mapping = aes(x = se_rob, linetype = "Robust")) +
  scale_linetype_manual(
    "Standardfehler",
    values = c("Nicht robust" = "solid", 
               "Robust" = "dashed")
  ) +
  theme_cowplot() +
  labs(title = "Standardfehler bei Heteroskedastizität") +
  theme(legend.position = "top")</code></pre>
<p>Als Konsequenz falscher Standardfehler kann die nominale <span class="math inline">\(\alpha\)</span>-Fehlerrate von Signifikanztests verletzt sein: Der Hypothesentest lehnt dann eine korrekte Nullhypothese mit einer geringeren oder höheren Fehlerwahrscheinlichkeit (das nominale Signifikanzniveau <span class="math inline">\(\alpha\)</span>) als gewünscht ab.</p>
<p>Inwiefern die in der Simulation gewählte Form von Heteroskedastizität die <span class="math inline">\(\alpha\)</span>-Fehlerrate eines t-Tests beeinflusst, können wir anhand der Simulationsergebnisse schätzen: Wir berechnen die Ablehnrate für t-Tests der (wahren) Null-Hypothese <span class="math inline">\(H_0:\beta_1=0\)</span> zum 5%-Niveau jeweils für robuste und nicht-robuste Standardfehler und vergleichen. Wir vergleichen die so berechneten Test-Statistiken mit dem entsprechenden kritischen Wert der t-Verteilung mit <span class="math inline">\(n-1\)</span> Freiheitsgraden.</p>
<pre class="{webr-r}"><code>#| autorun: true
# kritischer Wert der t_n-1-Verteilung
tcrit &lt;- qt(p = .975, df = n - 1)

# Ablehnrate des t-Tests schätzen
sim_res_het %&gt;%
  summarise(
    # alpha-Fehler der Tests schätzen
    alpha_err_h = mean(abs(beta/se) &gt; tcrit),
    alpha_err_r = mean(abs(beta/se_rob) &gt; tcrit)
  )</code></pre>
<p>Die Simulationsergebnisse deuten darauf hin, dass ein Fehler erster Art für den Signifikanztest ohne korrigierte Standardfehler oberhalb des 5%-Niveaus liegt. Für die robuste Teststatistik hingegen liegt die Schätzung des <span class="math inline">\(\alpha\)</span>-Fehlers nahe 5%.</p>
</section>
<section id="der-bootstrap" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="der-bootstrap"><span class="header-section-number">5.4</span> Der Bootstrap</h2>
<p>In den zuvor diskutierten Simulationsstudien haben wir iterativ Stichproben basierend auf einem bekannten DGP generiert, um die Eigenschaften der Stichprobenverteilung eines Schätzers (für bestimmte Parameterwerte) zu untersuchen. Der Bootstrap <span class="citation" data-cites="Efron1979">(<a href="Literatur.html#ref-Efron1979" role="doc-biblioref">Efron 1979</a>)</span> ist eine Methode zur Approximation der unbekannten Stichprobenverteilung eines Schätzers, bei der zufällige Stichproben mit Zurücklegen aus einer beobachteten Stichprobe gezogen werden.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a> Bootstrapping approximiert die Verteilung eines Schätzers aus beobachteten Datenpunkten und <em>ohne Kenntnis des wahren DGP</em>. Der Bootstrap ist daher eine Simulationsmethode, die in empirischen Anwendungen für die Bestimmung der Unsicherheit (Standardfehler) eines Schätzers genutzt werden kann. Bootstrapping ist hilfreich für Hypothesentests, wenn die beobachtete Stichprobe klein oder untypisch ist, was dazu führen kann, dass Standard-Inferenz für Behandlungseffekte nicht zuverlässig anwendbar oder ungültig ist. Insbesondere wenn Modellannahmen verletzt sind wird bootstrapping häufig in empirischen Studien eingesetzt, um Konfidenzintervalle, Standardfehler oder p-Werte zu berechnen.</p>
<p>Die nachfolgenden Key Facts fassen die wesentlichen Eigenschaften des Bootstraps und die grundsätzliche Vorgehensweise zusammen.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Key Facts zum Bootstrap
</div>
</div>
<div class="callout-body-container callout-body">
<p>Der Bootstrap ist eine statistische Methode, die durch wiederholtes Ziehen von Stichproben mit Zurücklegen aus einer beobachteten Stichprobe die Stichprobenverteilung eines Schätzers approximieren kann. Bootstrapping ermöglicht die Berechnung gültiger Inferenzstatistiken, ohne starke Annahmen über den zugrundeliegenden unbekannten DGP zu treffen.</p>
<p><strong>Vorgehensweise</strong></p>
<ol type="1">
<li><p><strong>Stichproben mit Zurücklegen ziehen</strong>: Ziehe wiederholt (<span class="math inline">\(B\)</span> mal) Stichproben der Größe <span class="math inline">\(N\)</span> (Größe der ursprünglichen Stichprobe) mit Zurücklegen aus der originalen Stichprobe.</p></li>
<li><p><strong>Parameterschätzung für jede Bootstrap-Stichprobe</strong>: Wende die Schätzfunktion <span class="math inline">\(\widehat{\beta}\)</span> auf jede der <span class="math inline">\(B\)</span> Bootstrap-Stichproben an und erhalte <span class="math inline">\(B\)</span> Bootstrap-Schätzwerte <span class="math inline">\(\widehat{\beta}^1,\dots,\widehat{\beta}^B\)</span> des interessierenden Koeffizienten <span class="math inline">\(\beta\)</span>.<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a></p></li>
<li><p><strong>Verteilungsparameter Schätzen</strong>: Anhand der <span class="math inline">\(B\)</span> Bootstrap-Schätzungen aus Schritt 2 können die Eigenschaften der Verteilung des Schätzers <span class="math inline">\(\widehat{\beta}\)</span> (oder für Funktionen von <span class="math inline">\(\widehat{\beta}\)</span>) geschätzt werden:</p>
<ul>
<li>Das arithmetische Mittel der <span class="math inline">\(B\)</span> Bootstrap-Schätzungen ist ein konsistenter Schätzer des Erwartungswerts von <span class="math inline">\(\widehat{\beta}\)</span></li>
<li>Der Standardfehler des Schätzers <span class="math inline">\(\widehat{\beta}\)</span> kann durch die Standardabweichung der <span class="math inline">\(B\)</span> Bootstrap-Schätzungen approximiert werden</li>
<li>Ein <span class="math inline">\(1-\alpha\%\)</span>-Bootstrap-Konfidenzintervall für <span class="math inline">\(\beta_1\)</span> kann anhand des <span class="math inline">\(\alpha/2\%\)</span>- und des <span class="math inline">\(1-\alpha/2\%\)</span>-Perzentils der Bootstrap-Verteilung approximiert werden</li>
</ul></li>
</ol>
<ul>
<li><p>Bootstrapping wird häufig genutzt, um die Unsicherheit eines Schätzers zu ermitteln. Dies ist insbesondere dann hilfreich, wenn keine analytische Darstellung für die Verteilung eines Schätzers existiert oder “starke” Verteilungsannahmen (z.B. Normalverteilung) unplausibel sind.</p></li>
<li><p>Ein Bootstrap-Schätzer für einen unbekannten Parameter<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a> ist im Allgemeinen <em>nicht erwartungstreu</em> für den interessierenden Effekt, selbst wenn ein erwartungstreuer Schätzer verwendet wird. Bootstrap-Schätzer sind jedoch in vielen Fällen unter schwachen Annahmen <em>konsistent</em> für den wahren Parameter.</p></li>
</ul>
</div>
</div>
<p>Der nächste Abschnitt diskutiert Bootstrapping der Stichprobenverteilung von <span class="math inline">\(\overline{X}\)</span> anhand des Beispiels aus <a href="#sec-simspv" class="quarto-xref"><span>Kapitel 5.1</span></a>.</p>
<section id="interaktive-visualisierung-des-bootstraps" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="interaktive-visualisierung-des-bootstraps"><span class="header-section-number">5.4.1</span> Interaktive Visualisierung des Bootstraps</h3>
<p>Die nachfolgende interaktive Visualisierung illustriert die Vorgehensweise des oben beschriebenen Bootstrap-Algorithmus für die Schätzung eines <span class="math inline">\(95\%\)</span>-Konfidenzintervalls für den Erwartungswert einer normalen <span style="color: purple;">Verteilung</span> basierend auf einer <span style="color: red;">Stichprobe</span>, wenn das arithmetische Mittel als Schätzer verwendet wird. Diese <span style="color: purple;">Pupulationsverteilung</span> ist <span class="math inline">\(N(\mu = 50, \sigma^2 = 12^2)\)</span>. In jeder Iteration des Bootstraps wird eine <span style="color: orange;">Bootstrap-Stichprobe</span> mit Zurücklegen aus der originalen <span style="color: red;">Stichprobe</span> gezogen. Für jede <span style="color: orange;">Bootstrap-Stichprobe</span> berechnen wir das <span style="color: darkgreen;">Arithmetische Mittel (grüne Punkte)</span>. Für hinreichend viele <span style="color: darkgreen;">Bootstrap-Schätzungen</span> erhalten wir eine repräsentative <span style="color: darkgreen;">Bootstrap-Verteilung</span> unseres Schätzers.<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a> Basierend auf dieser Verteilung berechnen wir eine <span style="color: black;">Bootstrap-Schätzung des Erwartungswerts</span> <span class="math inline">\(\mu\)</span> (schwarzer Punkt) und ein <span style="color: black;"><span class="math inline">\(95\%\)</span>-Konfidenzintervall</span> (schwarze Linie).</p>
<p>In der interaktiven Grafik können wir insbesondere folgende Eigenschaften des Bootstrap-Verfahrens überprüfen:</p>
<ul>
<li><p>Die <span style="color: purple;">Populationsverteilung</span> ist normal. Daher ist auch die Stichproben-Verteilung des arithmetischen Mittels <span class="math inline">\(\overline{X}\)</span> für <em>jede</em> Stichprobengröße normal. Die Illustration zeigt, dass die <span style="color: darkgreen;">Bootstrap-Verteilung</span> diese Normalverteilung des Schätzers (die typische Glockenform) tatsächlich gut approximieren kann, wenn <span class="math inline">\(B\)</span> hinreichend groß gewählt wird.</p></li>
<li><p>Der Bootstrap-Schätzer von <span class="math inline">\(\mu\)</span> ist nicht erwartungstreu für <span class="math inline">\(\mu\)</span>, da wir mit Zurückziehen aus einer <span style="color: red;">Stichprobe</span> ziehen und so die zentrale Tendenz in den beobachteten Daten reproduzieren. Diese Verzerrung verringert sich mit der Größe der <span style="color: red;">originalen Stichprobe</span>.</p></li>
<li><p>Größere <span style="color: red;">Stichproben</span> verringern die Unsicherheit des interessierenden Schätzers <span class="math inline">\(\overline{X}\)</span>: Die Varianz der Stichprobenverteilung von <span class="math inline">\(\overline{X}\)</span> nimmt mit der Stichprobengröße ab. Da der Bootstrap die Verteilung von <span class="math inline">\(\overline{X}\)</span> approximiert, spiegelt sich diese Eigenschaft auch in der <span style="color: darkgreen;">Bootstrap-Verteilung</span>.</p></li>
</ul>
<iframe class="obs-soft-box-shadow" width="100%" height="668" frameborder="0" src="https://observablehq.com/embed/62d24833f3dbd27a?cells=svg%2Cviewof+B%2Cviewof+BW%2Cviewof+speed%2Cviewof+n">
</iframe>
</section>
<section id="bootstrap-mit-r-durchführen" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="bootstrap-mit-r-durchführen"><span class="header-section-number">5.4.2</span> Bootstrap mit R durchführen</h3>
<p>Mit dem R-Paket <code>boot</code> kann Bootstrapping komfortabel für eine selbst definierte Schätzfunktion durchgeführt werden. Diese Funktion (<code>boot_fun</code> im nachfolgenden Code-Beispiel) muss den Schätzer unter Angabe einer Indexmenge für die beobachteten Daten berechnen und zurückgeben.<a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a></p>
<p>Der nächste Code-Chunk zeigt, wie <code>boot::boot()</code> angewendet werden kann, um den Bootstrap von <span class="citation" data-cites="Efron1979">Efron (<a href="Literatur.html#ref-Efron1979" role="doc-biblioref">1979</a>)</span> für <span class="math inline">\(\overline{X}\)</span> anhand einer Stichprobe mit <span class="math inline">\(n=250\)</span> aus der in <a href="#sec-simspv" class="quarto-xref"><span>Kapitel 5.1</span></a> betrachteten <span class="math inline">\(N(\mu = 50, \sigma^2 = 12^2)\)</span>-Populationsverteilung für <span class="math inline">\(B=999\)</span> Iterationen zu berechnen.</p>
<pre class="{webr-r}"><code>#| autorun: true
library(boot)

set.seed(1234)

# Parameter festlegen
n &lt;- 250
B &lt;- 999

# Stichprobe erzeugen
stichprobe &lt;- rnorm(
  n = n, 
  mean = 50,
  sd = 12
)

# Schätzfunktion definieren
boot_fun &lt;- \(dat, indizes) mean(dat[indizes])

# Bootstrap durchführen
(
  boot_est &lt;- boot(
    data = stichprobe, 
    statistic = boot_fun, 
    R = B
  )
)</code></pre>
<p>Der Output in <code>boot_est</code> beinhaltet die Schätzung von <span class="math inline">\(\mu\)</span> mit <span class="math inline">\(\overline{X}\)</span> anhand der originalen Stichprobe (<code>original</code>), eine Schätzung der Verzerrung von <span class="math inline">\(\overline{X}\)</span> (<code>bias</code>) sowie den Bootstrap-Standardfehler (<code>std. error</code>). Wir können die Berechnung dieser Maße mit der originalen Stichprobe sowie den Bootstrap-Berechnungen von <span class="math inline">\(\overline{X}\)</span> (<code>boot_est$t</code>) nachvollziehen.</p>
<pre class="{webr-r}"><code>#| autorun: true
# Stichprobenmittel (originale Stichprobe)
mean(stichprobe) # äquiv. zu boot_est$t0

# Bootstrap-Schätzer für Erwartungswert
mean(boot_est$t)

# 'bias'
mean(boot_est$t) - mean(stichprobe)

# Bootstrap-Standardfehler
sd(boot_est$t)</code></pre>
<p>Die Bootstrap-Verteilung von <span class="math inline">\(\overline{X}\)</span> ist recht gut mit der tatsächlichen <span class="math inline">\(N(\mu=50,\sigma^2 = 12^2/250)\)</span>-Stichprobenverteilung vergleichbar.</p>
<pre class="{webr-r}"><code>#| autorun: true
# Verteilung der Bootstrap-Mittelwerte plotten
tibble(mu_boot = boot_est$t) %&gt;%
  ggplot() +
  # Kerndichteschätzung der Bootstrap-Verteilung
  geom_density(
    mapping = aes(x = mu_boot)
  ) +
  # Wahre Stichprobenverteilung
  stat_function(
    fun = dnorm, 
    args = list(
      mean = 50, 
      sd = 12/sqrt(n)
    ), 
    color = "red",
    lty = 2
  ) +
  labs(title = "Vergleich von Bootstrap- und wahrer Stichprobenverteilung") +
  theme_cowplot()</code></pre>
<p>Mit <code>boot::boot.ci()</code> erhalten wir ein symmetrisches 95%-Bootstrap-Konfidenzintervall für <span class="math inline">\(\mu\)</span>, <span class="math display">\[\begin{align}
  95\%\textup{-KI}_\textup{boot} = \big[2\cdot \overline{X}_o - q_{.975,\,\textup{boot}}, \ 2\cdot \overline{X}_o - q_{.025,\,\textup{boot}}\big].\label{eq:95bootci}
\end{align}\]</span></p>
<pre class="{webr-r}"><code>#| autorun: true
# 95%-Bootstrap-KI
boot.ci(
  boot.out = boot_est, 
  type = "basic"
)</code></pre>
<p>Für die Berechnung per Hand mit der Formel <span class="math inline">\(\eqref{eq:95bootci}\)</span> bestimmen wir die Quantile der Bootstrap-Verteilung mit der Funktion <code>quantile()</code>.</p>
<pre class="{webr-r}"><code>#| autorun: true
# 95%-Bootstrap-KI 'per Hand' berechnen
(
  KI_boot &lt;- 2 * boot_est$t0 - quantile(boot_est$t, probs = c(.975, .025))
)</code></pre>
<p>Anhand dieses Konfidenzintervalls können wir Hypothesen zum 5%-Niveau testen.</p>
<pre class="{webr-r}"><code>#| autorun: true
# H_0: mu = 50 testen
between(50, KI_boot[1], KI_boot[2])</code></pre>
<p>Wir können die (wahre) Nullhypothese <span class="math inline">\(H_0: \mu = 50\)</span> also zum 5%-Niveau nicht ablehnen.</p>
</section>
</section>
<section id="zusammenfassung" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Zusammenfassung</h1>
<p>In diesem Kapitel haben wir Simulation zur Analyse der Eigenschaften von Koeffizientenschätzern in ökonometrischen Modellen betrachtet. In Simulationen können die Eigenschaften eines datenerzeugenden Prozesses vollständig kontrolliert und variiert werden, um deren Auswirkungen auf das Verhalten des Schätzers systematisch zu untersuchen. Simulation kann genutzt werden, um die Verteilung eines Schätzers näherungsweise durch iterative Berechnung von Schätzungen auf simulierten Datensätzen zu bestimmen. Solche Approximationen sind hilfreich, da analytische Lösungen für die Verteilungseigenschaften von Schätzfunktionen oft nicht verfügbar sind. Simulationen sind außerdem hilfreich, um verschiedene Schätzer hinsichtlich ihrer Güte bei Verletzungen von Modellannahmen zu bewerten und so Empfehlungen bezüglicher ihrer Verlässlichkeit in empirischen Anwendungen treffen zu können.</p>
<p>Der Bootstrap ist eine Simulationsmethode, die es ermöglicht, die Unsicherheit eines Schätzers im empirischen Anwenungen ohne starke Verteilungsannahmen abzuschätzen. Bootstrapping ist besonders nützlich in Situationen, in denen herkömmliche Inferenz versagt, weil die Approximationen mit einer asymptotischen Verteilung aufgrund zu kleiner Stichprobengröße schlecht ist, oder die asymptotische Verteilung unbekannt ist. Der Bootstrap wird in empirischen Studien häufig zur Berechnung verlässlicher Konfidenzintervalle für kausale Effekte angewendet.</p>
<p>Die gezeigten Code-Beispiele illustrieren die Anwendung dieser Techniken mit R.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Efron1979" class="csl-entry" role="listitem">
Efron, B. 1979. <span>„Bootstrap Methods: Another Look at the Jackknife“</span>. <em>The Annals of Statistics</em> 7 (1). <a href="https://doi.org/10.1214/aos/1176344552">https://doi.org/10.1214/aos/1176344552</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Englische Abkürzung für <em>data generating process</em>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>D.h. hier ist <span class="math inline">\(\overline{X}\sim N(50, 2.88)\)</span>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Iteration mit Funktionen aus dem Paket <code>purrr</code> (siehe tab) ist eine Alternative zum “klassischen” Ansatz mit einer <code>for()</code>-Schleife.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Ist <span class="math inline">\(X\)</span> log-normal-verteilt mit Erwartungswert <span class="math inline">\(\mu_X\)</span> und Varianz <span class="math inline">\(\sigma_X^2\)</span>, dann ist <span class="math inline">\(\log X\)</span> normal-verteilt mit <span class="math inline">\(\mu_{\log X} = \log \mu_X - \sigma_X^2/2\)</span> und <span class="math inline">\(\sigma^2_{\log X} = \mu_X^2 [\exp(\sigma_X^2)-1]\)</span>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><span class="math inline">\(\mathcal{U}[a,b]\)</span> meint die stetige <a href="https://de.wikipedia.org/wiki/Gleichverteilung">Gleichverteilung</a> auf dem Intervall <span class="math inline">\([a,b]\)</span><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Die Verzerrung (engl. <em>bias</em>) eines Schätzers <span class="math inline">\(\widehat{\beta}_1\)</span> für <span class="math inline">\(\beta_1\)</span> ist <span class="math inline">\(\textup{bias}(\widehat{\beta}_1) = \textup{E}(\widehat{\beta}_1 - \beta_1)\)</span>.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Anonyme Funktionen in R (auch <em>Lambda-Funktionen</em> genannt) sind Funktionen, die ohne Namen definiert werden und in der Regel sofort angwendet werden. <code>~</code> ist eine Kurznotation für anonyme Funktionen innerhalb von <code>purrr</code>-Funktionen.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>Die ist die Kern-Aussage des <a href="https://de.wikipedia.org/wiki/Satz_von_Gau%C3%9F-Markow">Gauss-Markov-Theorems</a>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Engl. <em>weighted least squares</em>.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>Der Typ <code>HC1</code>, auch bekannt als Huber-White-Schätzer, ist ein häufig genutzter Standardfehler und wird in späteren Kapiteln dieses Companions häufig angewendet.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Diese Vorgehensweise wird auch als <em>resampling</em> bezeichnet.<a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Häufig wird für <span class="math inline">\(B\)</span> eine ungerade Anzahl (z.B. 199) gewählt. Dies ermöglicht ein genaue Bestimmung des Medians der Bootstrap-Verteilung, was die Berechnung von Konfidenzintervallen erleichtert.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>Das arithmetische Mittel von <span class="math inline">\(B\)</span> Bootstrap-Schätzwerten ist ein einfacher Bootstrap-Schätzer.<a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>Die Grüne Linie zeigt eine Kerndichte-Schätzung der Bootstrap-Verteilung. Die Bandweite dieser Schätzung kann in der Applikation variiert werden.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p><code>boot::boot()</code> zieht in jeder Bootstrap-Iteration mit Zurücklegen aus der Indexmenge der originalen Stichprobe, um die Bootstrap-Stichprobe festzulegen.<a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Reg.html" class="pagination-link" aria-label="Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Matching.html" class="pagination-link" aria-label="Matching">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Matching</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>